DELETE http://localhost:3003/api/blogs/6664aec395607d0208d26eb2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2NjY0Y2MyZTEwNjA3YjE5ZmY2YzQzZTEiLCJpYXQiOjE3MTc4OTQwNDgsImV4cCI6MTcxNzg5NzY0OH0.w5JkZngwt5r2NFthMNDPvrKDQhas3qPsHWaKgsgLdlU