name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install clientdependencies
        run: npm install --prefix ./bloglist/client
        
      - name: Install backend dependencies
        run: npm install --prefix ./bloglist/server
      
      - name: Check style
        run: npm run lint --prefix ./bloglist/client

      - name: Build client
        run: npm run build --prefix ./bloglist/client
      
      - name: Run server unit tests
        run: npm test --prefix ./bloglist/server
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          
      - name: Setup Playwright
        run: |
          npm ci
          npx playwright install --with-deps
        working-directory: bloglist/bloglist-e2e-tests
          
      - name: Start server in production mode
        run: npm run start-prod --prefix ./bloglist/server &
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: 3003
          SECRET: ${{ secrets.SECRET }}
      
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3003

      - name: Start client in development mode
        run: npm run dev --prefix ./client &
      
      - name: Wait for client to be ready
        run: npx wait-on http://localhost:3000
      
      - name: Run end-to-end tests
        run: npm t
        working-directory: bloglist/bloglist-e2e-tests
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
      
      - name: Trigger deployment
        if: ${{ github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        
      - name: Success notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'A new version has been built.'

      - name: Failure notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Build has failed. Commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build.'
